import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          '1': 'var(--chart-1)',
          '2': 'var(--chart-2)',
          '3': 'var(--chart-3)',
          '4': 'var(--chart-4)',
          '5': 'var(--chart-5)',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar)',
          foreground: 'var(--sidebar-foreground)',
          primary: 'var(--sidebar-primary)',
          'primary-foreground': 'var(--sidebar-primary-foreground)',
          accent: 'var(--sidebar-accent)',
          'accent-foreground': 'var(--sidebar-accent-foreground)',
          border: 'var(--sidebar-border)',
          ring: 'var(--sidebar-ring)',
        },
        brand: {
          50: 'var(--brand-50)',
          100: 'var(--brand-100)',
          200: 'var(--brand-200)',
          500: 'var(--brand-500)',
          600: 'var(--brand-600)',
          700: 'var(--brand-700)',
          800: 'var(--brand-800)',
          DEFAULT: 'var(--brand-primary)',
          primary: 'var(--brand-primary)',
          foreground: 'var(--brand-primary-foreground)',
          'primary-foreground': 'var(--brand-primary-foreground)',
          'primary-hover': 'var(--brand-primary-hover)',
          muted: 'var(--brand-muted)',
          'muted-foreground': 'var(--brand-muted-foreground)',
        },
        green: {
          50: 'var(--green-50, #f0fdf4)',
          100: 'var(--green-100, #dcfce7)',
          200: 'var(--green-200, #bbf7d0)',
          300: 'var(--green-300, #86efac)',
          400: 'var(--green-400, #4ade80)',
          500: 'var(--green-500, #22c55e)',
          600: 'var(--green-600, #16a34a)',
          700: 'var(--green-700, #15803d)',
          800: 'var(--green-800, #166534)',
          900: 'var(--green-900, #14532d)',
        },
        gray: {
          50: 'var(--gray-50, #f9fafb)',
          100: 'var(--gray-100, #f3f4f6)',
          200: 'var(--gray-200, #e5e7eb)',
          300: 'var(--gray-300, #d1d5db)',
          400: 'var(--gray-400, #9ca3af)',
          500: 'var(--gray-500, #6b7280)',
          600: 'var(--gray-600, #4b5563)',
          700: 'var(--gray-700, #374151)',
          800: 'var(--gray-800, #1f2937)',
          900: 'var(--gray-900, #111827)',
        },
        amber: {
          50: 'var(--amber-50, #fffbeb)',
          100: 'var(--amber-100, #fef3c7)',
          200: 'var(--amber-200, #fde68a)',
          300: 'var(--amber-300, #fcd34d)',
          400: 'var(--amber-400, #fbbf24)',
          500: 'var(--amber-500, #f59e0b)',
          600: 'var(--amber-600, #d97706)',
          700: 'var(--amber-700, #b45309)',
          800: 'var(--amber-800, #92400e)',
          900: 'var(--amber-900, #78350f)',
        },
        red: {
          50: 'var(--red-50, #fef2f2)',
          100: 'var(--red-100, #fee2e2)',
          200: 'var(--red-200, #fecaca)',
          300: 'var(--red-300, #fca5a5)',
          400: 'var(--red-400, #f87171)',
          500: 'var(--red-500, #ef4444)',
          600: 'var(--red-600, #dc2626)',
          700: 'var(--red-700, #b91c1c)',
          800: 'var(--red-800, #991b1b)',
          900: 'var(--red-900, #7f1d1d)',
        },
        blue: {
          50: 'var(--blue-50, #eff6ff)',
          100: 'var(--blue-100, #dbeafe)',
          200: 'var(--blue-200, #bfdbfe)',
          300: 'var(--blue-300, #93c5fd)',
          400: 'var(--blue-400, #60a5fa)',
          500: 'var(--blue-500, #3b82f6)',
          600: 'var(--blue-600, #2563eb)',
          700: 'var(--blue-700, #1d4ed8)',
          800: 'var(--blue-800, #1e40af)',
          900: 'var(--blue-900, #1e3a8a)',
        },
        status: {
          danger: 'var(--status-danger)',
          'danger-muted': 'var(--status-danger-muted)',
          'danger-border': 'var(--status-danger-border)',
          info: 'var(--status-info)',
          'info-muted': 'var(--status-info-muted)',
          'info-border': 'var(--status-info-border)',
          success: 'var(--status-success)',
          'success-muted': 'var(--status-success-muted)',
          'success-border': 'var(--status-success-border)',
          warning: 'var(--status-warning)',
          'warning-muted': 'var(--status-warning-muted)',
          'warning-border': 'var(--status-warning-border)',
        },
        surface: {
          page: 'var(--surface-page)',
          elevated: 'var(--surface-elevated)',
          subtle: 'var(--surface-subtle)',
          border: 'var(--surface-border)',
          topbar: 'var(--surface-topbar)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
    },
  },
  plugins: [],
};

export default config;
