'use client';

import React from 'react';

interface CreateAdminPageProps {
  onBack?: () => void;
}

export default function CreateAdminPage({ onBack }: CreateAdminPageProps) {
  const [email, setEmail] = React.useState('');
  const [fullName, setFullName] = React.useState('');
  const [council, setCouncil] = React.useState('');
  const [contactNumber, setContactNumber] = React.useState('');
  const [error, setError] = React.useState('');
  const [success, setSuccess] = React.useState('');
  const [loading, setLoading] = React.useState(false);

  const API_BASE = process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:8080';

  // Admin list fetching moved to AdminAssignment; CreateAdminPage only handles creation

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');
    if (!fullName.trim() || !email.trim() || !council.trim()) {
      setError('Full name, email, and council are required');
      return;
    }
    // Duplicate email check moved to AdminAssignment (All Users table)
    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const res = await fetch(`${API_BASE}/api/users`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({
          fullName: fullName.trim(),
          email: email.trim(),
          contactNumber: contactNumber.trim() || undefined,
          council: council.trim(),
        }),
      });
      const json = await res.json();
      if (!res.ok) {
        setError(json?.message || 'Failed to create admin');
      } else if (json.success) {
        setSuccess('Admin created successfully!');
        setFullName('');
        setEmail('');
        setContactNumber('');
        setCouncil('');
        if (onBack) setTimeout(onBack, 1000);
      } else {
        setError('Failed to create admin');
      }
    } catch (err: any) {
      setError('Network error. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-md mx-auto mt-12 bg-white p-8 rounded shadow relative">
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-bold">Create New Admin</h2>
        {onBack && (
          <button
            type="button"
            onClick={onBack}
            aria-label="Close"
            className="text-gray-500 hover:text-red-500 cursor-pointer text-xl"
          >
            ×
          </button>
        )}
      </div>
      <form onSubmit={handleSubmit} className="space-y-4">
          {/* Existing admins list removed — handled in AdminAssignment's All Users table */}
        <div>
          <label className="block mb-1 font-medium">Full Name</label>
          <input
            className="w-full border rounded px-3 py-2"
            type="text"
            value={fullName}
            onChange={e => setFullName(e.target.value)}
            required
          />
        </div>
        <div>
          <label className="block mb-1 font-medium">Email</label>
          <input
            className="w-full border rounded px-3 py-2"
            type="email"
            value={email}
            onChange={e => setEmail(e.target.value)}
            required
          />
        </div>
        <div>
          <label className="block mb-1 font-medium">Contact Number</label>
          <input
            className="w-full border rounded px-3 py-2"
            type="tel"
            value={contactNumber}
            onChange={e => setContactNumber(e.target.value)}
          />
        </div>
        {/* Password is generated by backend and emailed; no input needed */}
        <div>
          <label className="block mb-1 font-medium">Council</label>
          <select
            className="w-full border rounded px-3 py-2"
            value={council}
            onChange={e => setCouncil(e.target.value)}
            required
          >
            <option value="" disabled>
              Select Council
            </option>
            <option value="Colombo">Colombo</option>
            <option value="Kandy">Kandy</option>
            <option value="Galle">Galle</option>
            <option value="Gampaha">Gampaha</option>
            <option value="Matara">Matara</option>
          </select>
        </div>
        {error && <div className="text-red-600 text-sm">{error}</div>}
        {success && <div className="text-green-600 text-sm">{success}</div>}
        <div className="flex justify-center mt-8">
          <button
            type="submit"
            className="bg-black text-white font-bold text-lg px-8 py-3 rounded shadow-lg hover:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-black transition"
            style={{ minWidth: 180 }}
            disabled={loading}
          >
            {loading ? 'Creating...' : 'Create Admin'}
          </button>
        </div>
      </form>
    </div>
  );
}
